name: Check for appropriate test coverage and run unit tests.

on:
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Run coverage
        run: yarn coverage
      - name: Run unit tests
        run: yarn test